# Opciones de la Máquina Virtual de Java para acelerar la compilación
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Soporte obligatorio para librerías modernas de AndroidX
android.useAndroidX=true

# Optimización del espacio de nombres de recursos
android.nonTransitiveRClass=true

# Deshabilitar Jetifier ya que no se utilizan librerías legadas de soporte antiguo
android.enableJetifier=false
