plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tubevideos'
    compileSdk 34

    defaultConfig {
        applicationId "com.tubevideos"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        // Soporte nativo de arquitecturas para ejecutable yt-dlp
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'com.google.android.gms:play-services-ads:23.0.0'

    // Librerías yt-dlp para Android
    implementation 'com.github.yausername.youtubedl-android:library:0.17.0'
    implementation 'com.github.yausername.youtubedl-android:ffmpeg:0.17.0'
}
